import { Rocket, Code2, Star, Award } from 'lucide-react'

export const getAllAchievements = (t: (key: string) => string) => [
  {
    id: 1,
    slug: 'vulkan-render-engine',
    titleKey: 'projects.vulkan.title',
    descriptionKey: 'projects.vulkan.description',
    tech: ['C++', 'Vulkan API', 'GLSL', 'CMake'],
    link: 'https://github.com/AndreeSalazar/Motor-de-Render-Minimalista',
    icon: Rocket,
    color: 'from-blue-500 to-cyan-500',
    featured: true,
  },
  {
    id: 2,
    slug: 'omega-visual-web',
    titleKey: 'projects.omegaWeb.title',
    descriptionKey: 'projects.omegaWeb.description',
    tech: ['Angular', 'TypeScript', 'RxJS', 'CSS3'],
    link: 'https://andreesalazar.github.io/Omega-Visual-Web/',
    icon: Code2,
    color: 'from-purple-500 to-pink-500',
    featured: true,
    isWeb: true,
  },
  {
    id: 3,
    slug: 'codermind-visual',
    titleKey: 'projects.codermind.title',
    descriptionKey: 'projects.codermind.description',
    tech: ['Python', 'PyQt', 'Node System'],
    link: 'https://github.com/AndreeSalazar/Omega-Visual-Semantic-Node-Based-Code-Editor',
    icon: Code2,
    color: 'from-orange-500 to-red-500',
    isBase: true,
    highlightKeys: [
      'projects.codermind.highlight1',
      'projects.codermind.highlight2',
      'projects.codermind.highlight3',
    ],
  },
  {
    id: 4,
    slug: 'ultra-omega',
    titleKey: 'projects.ultraOmega.title',
    descriptionKey: 'projects.ultraOmega.description',
    tech: ['Rust', 'EGUI', 'wgpu', t('projects.tech.multiplataforma')],
    link: 'https://github.com/AndreeSalazar/Omega-Visual-Semantic-Node-Based-Code-Editor',
    icon: Star,
    color: 'from-amber-500 to-yellow-500',
    featured: true,
    highlightKeys: [
      'projects.ultraOmega.highlight1',
      'projects.ultraOmega.highlight2',
      'projects.ultraOmega.highlight3',
      'projects.ultraOmega.highlight4',
      'projects.ultraOmega.highlight5',
    ],
  },
  {
    id: 5,
    slug: 'omega-desktop',
    titleKey: 'projects.omegaDesktop.title',
    descriptionKey: 'projects.omegaDesktop.description',
    tech: ['Python', 'C++', 'Vulkan', 'Qt'],
    link: 'https://github.com/AndreeSalazar/Omega-Visual-Semantic-Node-Based-Code-Editor',
    icon: Code2,
    color: 'from-gray-500 to-slate-500',
    isLegacy: true,
    highlightKeys: [
      'projects.omegaDesktop.highlight1',
      'projects.omegaDesktop.highlight2',
      'projects.omegaDesktop.highlight3',
    ],
  },
  {
    id: 6,
    slug: 'professional-portfolio',
    titleKey: 'projects.portfolio.title',
    descriptionKey: 'projects.portfolio.description',
    tech: ['HTML5', 'CSS3', 'JavaScript'],
    link: 'https://github.com/AndreeSalazar/Web-Portfolio-Personal-1',
    icon: Award,
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: 7,
    slug: 'fastos',
    titleKey: 'projects.fastOS.title',
    descriptionKey: 'projects.fastOS.description',
    tech: ['ASM (NASM)', 'C', 'Vulkan API', '64-bit'],
    link: null,
    demoImage: '/images/fastos-demo.png',
    icon: Rocket,
    color: 'from-indigo-500 to-purple-500',
    featured: true,
    highlightKeys: [
      'projects.fastOS.highlight1',
      'projects.fastOS.highlight2',
      'projects.fastOS.highlight3',
      'projects.fastOS.highlight4',
    ],
    motivationKey: 'projects.fastOS.motivation',
    learnedKey: 'projects.fastOS.learned',
    challengesKey: 'projects.fastOS.challenges',
    resultsKey: 'projects.fastOS.results',
  },
  {
    id: 8,
    slug: 'graphics-engine-test',
    titleKey: 'projects.graphicsEngine.title',
    descriptionKey: 'projects.graphicsEngine.description',
    tech: ['C++', 'Vulkan API', 'Vector Math', '2D/3D'],
    link: null,
    demoImage: '/images/graphics-engine-demo.png',
    icon: Code2,
    color: 'from-cyan-500 to-blue-500',
    featured: true,
    highlightKeys: [
      'projects.graphicsEngine.highlight1',
      'projects.graphicsEngine.highlight2',
      'projects.graphicsEngine.highlight3',
    ],
    motivationKey: 'projects.graphicsEngine.motivation',
    learnedKey: 'projects.graphicsEngine.learned',
    challengesKey: 'projects.graphicsEngine.challenges',
    resultsKey: 'projects.graphicsEngine.results',
  },
]
